# Example Makefile for statistical workflows
# Author: Jonathan McMahon  
.PHONY : all regression plot clean

# We can change the filename by passing this as a command-line arg  
DATASET?=data.csv


# Run 'plot' target, then 'regression' target
all: plot regression

# Remove files generated by make process
clean:
	rm -f plot.png test.log $(DATASET)

# Call a script and pass it an argument
regression: $(DATASET)
	Rscript regression.R $(DATASET)

# Shortcut for plot.png
plot: plot.png

# Plot.png is dependent on data.csv and generate_plot.R;
# if either of those have changed, run this target to generate
# an updated plot.png
plot.png: $(DATASET) generate_plot.R
	Rscript generate_plot.R $(DATASET)

# Variables example
$(DATASET):
	Rscript scrape_data.R $(DATASET)

# Automatic variables example
%.R: $(DATASET)
	@echo "target: $@ \t dependencies: $^ \t first dependency: $<"
	Rscript $@ $(DATASET)
